sudo: required
dist: trusty
language: generic
services: docker

# auto-updates docker engine
addons:
  apt:
    packages:
      - docker-ce

script:
  - sudo service docker restart
  - cd ${TRAVIS_BUILD_DIR}
  - travis_wait 45 make ${SUBDIR}
  - |
    if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]] ; then
        docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
        make push_${SUBDIR}
    fi

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - DOCKER_QUIET=-q
  matrix:
    - SUBDIR=debian_travis
  # disabled since it does not complete within travis' time limits
  # - SUBDIR=manylinux
    - SUBDIR=arch
    - SUBDIR=testing
